export const products = [
    {
        id: 1,
        title: 'Profissional de Digitação',
        description: 'O que você poderá fazer: digitar e formatar textos e artigos, criar ebooks, transcrever áudios para textos, realizar correções, criar roteiros, entre outras atividades que envolvem digitação.',
        value: 'R$ 49,90',
        returnValue: 'R$ 200 por serviço',
        dificult: 2,
        ranking: 4,
        url: 'digitacao',
        isHighligh: true,
        returnNumber: 3,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 2,
        title: 'Profissional de Redes Sociais',
        description: 'O que você poderá fazer: Criar post para redes sociais, entre outras artes gráficas como banners, panfletos, cardápios, logos e apresentações.',
        value: 'R$ 49,90',
        returnValue: 'R$ 350 por serviço',
        dificult: 3,
        ranking: 4,
        url: 'redes-sociais',
        isHighligh: true,
        returnNumber: 4,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 3,
        title: 'Assistente Virtual',
        description: 'O que precisa fazer: trabalhos administrativos, organização de planilhas, documentações, gerenciamento de email e organização de agenda.',
        value: 'R$ 49,90',
        returnValue: 'R$ 200 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'assistente-virtual',
        isHighligh: true,
        returnNumber: 3,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 4,
        title: 'Profissional de Pesquisas Online',
        description: 'O que precisa fazer: responder pesquisas, avaliar produtos e serviços.',
        value: 'R$ 59,00',
        returnValue: 'R$ 5 por pesquisa',
        dificult: 1,
        ranking: 2,
        url: 'pesquisa-online',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 5,
        title: 'Profissional de Tradução',
        description: 'O que você poderá fazer: traduções básicas, tradução de vídeos, ebooks, fazer dublagens em qualquer idioma, entre outras atividades que envolvem tradução.',
        value: 'R$ 49,90',
        returnValue: 'R$ 125 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'traducao',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 6,
        title: 'Profissional de Locução',
        description: 'O que você poderá fazer: realizar locuções para VSL’s, detalhe de locuções para Youtube, maneiras de editar suas locuções, técnicas vocais, etc.',
        value: 'R$ 49,90',
        returnValue: 'R$ 150 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'locucao',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 7,
        title: 'Profissional de Telemarketing',
        description: 'O que você poderá fazer: criar portfólio profissional, técnicas vocais, agendamento de reuniões, contato com clientes e fechamento de vendas.',
        value: 'R$ 49,90',
        returnValue: 'R$ 150 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'telemarketing',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 8,
        title: 'UGC Creator',
        description: 'O que você poderá fazer: produzir conteúdo para a marca, utilizar as redes sociais para otimizar seu trabalho, fazer seu primeiro vídeo, entre outras atividades que envolvem.',
        value: 'R$ 49,90',
        returnValue: 'R$ 300 por serviço',
        dificult: 3,
        ranking: 4,
        url: 'ugc-creator',
        isHighligh: false,
        returnNumber: 3,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 9,
        title: 'Assistente de Chat Suporte',
        description: 'O que você poderá fazer: trabalhar em outros idiomas, gerenciar e-mail, data entry, entre outras atividades que envolvem.',
        value: 'R$ 49,90',
        returnValue: 'R$ 200 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'assistente-chat-suporte',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 10,
        title: 'Agente de Chat',
        description: 'O que você poderá fazer: atendimento ao cliente via chat, resolver problemas, técnicas de satisfação do cliente, métricas de serviço, etc.',
        value: 'R$ 49,90',
        returnValue: 'R$ 200 por serviço',
        dificult: 3,
        ranking: 3,
        url: 'agente-chat',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 11,
        title: 'Profissional de Home Office',
        description: 'O que você poderá fazer: digitar e formatar textos e artigos, criar ebooks, transcrever áudios para textos, realizar correções, criar roteiros, entre outras atividades que envolvem.',
        value: 'R$ 49,90',
        returnValue: 'R$ 150 por serviço',
        dificult: 2,
        ranking: 4,
        url: 'home-office',
        isHighligh: false,
        returnNumber: 3,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 12,
        title: 'Empacotador Profissional',
        description: 'O que você poderá fazer: adicionar produtos no Shopify, fazer upload de um artigo no Wordpress, registrar de produtos na Amazon, analisar e registrar dados em sistemas, etc.',
        value: 'R$ 49,90',
        returnValue: 'R$ 100 por serviço',
        dificult: 2,
        ranking: 3,
        url: 'empacotador-profissional',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 13,
        title: 'Avaliador de Músicas',
        description: 'O que você poderá fazer: ouvir e avaliar músicas em plataformas e aplicativos que vão lhe pagar por isso.',
        value: 'R$ 49,90',
        returnValue: 'R$ 5 por música',
        dificult: 1,
        ranking: 2,
        url: 'avaliador-musicas',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 14,
        title: 'Avaliador de Vídeos',
        description: 'O que você poderá fazer: ouvir e avaliar vídeos em plataformas e aplicativos que vão lhe pagar por isso.',
        value: 'R$ 49,90',
        returnValue: 'R$ 5 por vídeo',
        dificult: 1,
        ranking: 2,
        url: 'avaliador-videos',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 15,
        title: 'Profissional de Pesquisas Online',
        description: 'O que precisa fazer: responder pesquisas, avaliar produtos e serviços.',
        value: 'R$ 59,00',
        returnValue: 'R$ 5 por pesquisa',
        dificult: 1,
        ranking: 2,
        url: 'pesquisas-online',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 16,
        title: 'Remunera App',
        description: 'O que você poderá fazer: revisar se existe algum problema em aplicativos e plataformas e ser pago por isso.',
        value: 'R$ 49,90',
        returnValue: 'R$ 10 por avaliação',
        dificult: 2,
        ranking: 3,
        url: 'remunera-app',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 17,
        title: 'Avaliador de Mídias',
        description: 'O que você poderá fazer: segmentar corretamente as palavras, páginas, endereços e publicações para melhorar a usabilidade do usuário ao fazer uma busca.',
        value: 'R$ 49,90',
        returnValue: 'R$ 10 por avaliação',
        dificult: 2,
        ranking: 3,
        url: 'avaliador-midias',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 18,
        title: 'Auxiliar de Produção',
        description: 'O que você poderá fazer: realizar procedimentos estabelecidos para garantir a eficiência e a qualidade do processo de embalagem.',
        value: 'R$ 49,90',
        returnValue: 'R$ 100 por serviço',
        dificult: 2,
        ranking: 3,
        url: 'auxiliar-producao',
        isHighligh: false,
        returnNumber: 2,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 19,
        title: 'Afiliado Digital',
        description: 'O que você poderá fazer: indicar produtos feitos por outras pessoas e receber comissões pelas vendas realizadas.',
        value: 'R$ 49,90',
        returnValue: 'R$ 50 por comissão',
        dificult: 3,
        ranking: 3,
        url: 'afiliado-digital',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 20,
        title: 'Cliente Oculto',
        description: 'O que você poderá fazer: fazer compras e avaliar secretamente a empresa onde a compra foi feita.',
        value: 'R$ 49,90',
        returnValue: 'R$ 30 por avaliação',
        dificult: 2,
        ranking: 3,
        url: 'cliente-oculto',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 21,
        title: 'Profissional de Milhas',
        description: 'O que você poderá fazer: introduzir conceitos de custo médio dinâmico, administração de estoque e gestão de contas.',
        value: 'R$ 49,90',
        returnValue: 'R$ 50 por avaliação',
        dificult: 3,
        ranking: 3,
        url: 'profissional-milhas',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    },
    {
        id: 22,
        title: 'Avaliador de Produtos',
        description: 'O que você poderá fazer: entrar em plataformas de avaliação e avaliar produtos em geral.',
        value: 'R$ 49,90',
        returnValue: 'R$ 10 por avaliação',
        dificult: 2,
        ranking: 3,
        url: 'avaliador-produtos',
        isHighligh: false,
        returnNumber: 1,
        top: 'Top 1 Custo-Benefício'
    }
];
